eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: localhost
    
management:
    info:
      env:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
